version: '2'

services:
  app:
    image: 'docker-spring-boot-postgres:latest'
    build:
      context: .
    container_name: app
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/projetc-manager
      - SPRING_DATASOURCE_USERNAME=conexao
      - SPRING_DATASOURCE_PASSWORD=conexao
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  db:
    image: 'postgres:13.1-alpine'
    container_name: db
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=projetc-manager
      - POSTGRES_PASSWORD=projetc-manager